/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/Article/ArticleCard.vue')['default']
    ArticleDetail: typeof import('./src/components/Article/ArticleDetail.vue')['default']
    ArticleList: typeof import('./src/components/Article/ArticleList.vue')['default']
    BackTop: typeof import('./src/components/common/BackTop.vue')['default']
    Comment: typeof import('./src/components/Comment/Comment.vue')['default']
    CommentSection: typeof import('./src/components/Comment/CommentSection.vue')['default']
    CommentTest: typeof import('./src/components/Comment/CommentTest.vue')['default']
    GlobalHeader: typeof import('./src/components/common/GlobalHeader.vue')['default']
    GloubalFooter: typeof import('./src/components/GloubalFooter.vue')['default']
    GloubalHeader: typeof import('./src/components/GloubalHeader.vue')['default']
    RichEditor: typeof import('./src/components/Article/RichEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UComment: typeof import('undraw-ui')['UComment']
    UCommentNav: typeof import('undraw-ui')['UCommentNav']
    UCommentScroll: typeof import('undraw-ui')['UCommentScroll']
  }
}

// For TSX support
declare global {
  const ArticleCard: typeof import('./src/components/Article/ArticleCard.vue')['default']
  const ArticleDetail: typeof import('./src/components/Article/ArticleDetail.vue')['default']
  const ArticleList: typeof import('./src/components/Article/ArticleList.vue')['default']
  const BackTop: typeof import('./src/components/common/BackTop.vue')['default']
  const Comment: typeof import('./src/components/Comment/Comment.vue')['default']
  const CommentSection: typeof import('./src/components/Comment/CommentSection.vue')['default']
  const CommentTest: typeof import('./src/components/Comment/CommentTest.vue')['default']
  const GlobalHeader: typeof import('./src/components/common/GlobalHeader.vue')['default']
  const GloubalFooter: typeof import('./src/components/GloubalFooter.vue')['default']
  const GloubalHeader: typeof import('./src/components/GloubalHeader.vue')['default']
  const RichEditor: typeof import('./src/components/Article/RichEditor.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UComment: typeof import('undraw-ui')['UComment']
  const UCommentNav: typeof import('undraw-ui')['UCommentNav']
  const UCommentScroll: typeof import('undraw-ui')['UCommentScroll']
}