/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/Article/ArticleCard.vue')['default']
    ArticleDetail: typeof import('./src/components/Article/ArticleDetail.vue')['default']
    ArticleList: typeof import('./src/components/Article/ArticleList.vue')['default']
    BackTop: typeof import('./src/components/common/BackTop.vue')['default']
    CommentSection: typeof import('./src/components/Comment/CommentSection.vue')['default']
    GlobalHeader: typeof import('./src/components/common/GlobalHeader.vue')['default']
    NewsCarousel: typeof import('./src/components/NewsCarousel/NewsCarousel.vue')['default']
    Operate: typeof import('./src/components/Comment/Operate.vue')['default']
    RichEditor: typeof import('./src/components/Article/RichEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TurnstileCaptcha: typeof import('./src/components/common/TurnstileCaptcha.vue')['default']
    UComment: typeof import('undraw-ui')['UComment']
    UCommentScroll: typeof import('undraw-ui')['UCommentScroll']
    UIcon: typeof import('undraw-ui')['UIcon']
  }
}

// For TSX support
declare global {
  const ArticleCard: typeof import('./src/components/Article/ArticleCard.vue')['default']
  const ArticleDetail: typeof import('./src/components/Article/ArticleDetail.vue')['default']
  const ArticleList: typeof import('./src/components/Article/ArticleList.vue')['default']
  const BackTop: typeof import('./src/components/common/BackTop.vue')['default']
  const CommentSection: typeof import('./src/components/Comment/CommentSection.vue')['default']
  const GlobalHeader: typeof import('./src/components/common/GlobalHeader.vue')['default']
  const NewsCarousel: typeof import('./src/components/NewsCarousel/NewsCarousel.vue')['default']
  const Operate: typeof import('./src/components/Comment/Operate.vue')['default']
  const RichEditor: typeof import('./src/components/Article/RichEditor.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TurnstileCaptcha: typeof import('./src/components/common/TurnstileCaptcha.vue')['default']
  const UComment: typeof import('undraw-ui')['UComment']
  const UCommentScroll: typeof import('undraw-ui')['UCommentScroll']
  const UIcon: typeof import('undraw-ui')['UIcon']
}