server:
  port: 8080

spring:
  datasource:
    # 单独配置数据库 MYSQl(因为使用manticore多个数据源)
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/miku_spring_boot
      username: root
      password: "REMOVED"
      pool-name: MySQLPool
      maximum-pool-size: 20

  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    # 全局日志拦截等级:warn (根据需求开启)
    root: warn
    com:
      miku:
        # 只打印业务模块日志 (根据需求开启)
        controller: info
        service: info

mybatis-plus:
  # 实体类别名包路径
  type-aliases-package: com.miku.entity
  # Mapper XML 文件路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启 MYSQL 驼峰映射
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 使用数据库自增id (使用MP会默认开启雪花id)
      id-type: auto


miku:
  jwt:
    # 用户端:
    # 设置jwt过期时间 (7天)
    user-ttl: 604800000
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: =
    # 设置前端传递过来的令牌名称
    user-token-name: tokename
    # 设置Cookie请求头名称
    cookie-name: access_token